
### create valid user data
POST http://localhost:3000/offline/api/em-create-user
Content-Type: application/json


{
    "name":"Subha",
    "email":"Subha11@gmail.com",
    "profile_pic":"https://subha.com",
    "currency":"INR"
}


### get user data
##update the User ID from the response of the above request
POST http://localhost:3000/offline/api/em-get-user
Content-Type: application/json

{
    "userID": "ac56ffa5-1c76-49d4-84a5-3a61423afc0b"
}

### update user data
##update the User ID from the response of the above request
PUT http://localhost:3000/offline/api/em-get-user
Content-Type: application/json

{
    "userID": "5a52489c-04f1-48d1-b90f-c3a7880eb168",
    "name":"Subhalakshmi Ravichandran",
    "profile_pic":"https://subha.com",
    "currency":"AED",
    "status":"ACTIVE"
}

### delete user data
##update the User ID from the response of the above request
DELETE  http://localhost:3000/offline/api/em-delete-user
Content-Type: application/json

{
    "userID": "ac56ffa5-1c76-49d4-84a5-3a61423afc0b",
    "status":"INACTIVE"
}

